apiVersion: v1
kind: Service
metadata:
  name: aks-demo-api-service
spec:
  type: LoadBalancer
  ports: 
  - port: 80 # Public port accessible from the browser
    targetPort: 8080 # Port exposed by Docker container
    protocol: TCP
  selector:
    app: aks-demo-api